import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./assets/scss/tailwind.scss";
import "./assets/scss/layout.scss";

const inter = Inter({ subsets: ["latin"] });

import { headers } from "next/headers";
import Web3ModalProvider from "./context/wagmi";
import { cookieToInitialState } from "wagmi";
import { config } from "./config/wagmi";
import Navbar from "./components/Navbar/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialState = cookieToInitialState(config, headers().get("cookie"));

    return (
        <html lang="en">
            <body className={inter.className}>
                <Web3ModalProvider initialState={initialState}>
                    <header>
                        <Navbar />
                    </header>
                    <main>{children}</main>
                </Web3ModalProvider>
            </body>
        </html>
    );
}
